### ISSUE TITLE
connect() failure on unix domain socket

### ISSUE THREAD

**Issue by kosmas-valianos** [axboe/liburing#486] opened 2021-11-26 08:52 UTC
I have noticed a strange behavior when using `IO_URING` and `io_uring_prep_connect`. In case a server listening on a unix domain socket goes down and the client tries to reconnect in the meantime in intervals, it never succeeds to reconnect despite the server being brought back. I wrote a simple program to demonstrate this behavior.

System:
Ubuntu 20.04.3 LTS
`5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### Test1: IO_URING
1. Set up a dummy unix domain socket server: `nc -U -l ./server.socket`
2. Connect using the `IO_URING` style: `./connect_test -u ./server.socket`
3. Close down the server
4. Connection goes down in client and it enters a retry at interval
5. Bring the server up with the same cmd as in step 1
6. Client never manages to re-establish connection. It keeps failing with the same error
```
Connection established
[4] Bytes read: 9
Connection closed: 0 Success
connect() failed: Connection refused
connect() failed: No such file or directory
connect() failed: No such file or directory
connect() failed: No such file or directory
connect() failed: No such file or directory
connect() failed: No such file or directory
connect() failed: No such file or directory
connect() failed: No such file or directory
connect() failed: No such file or directory
```

### Test2: Old school poll()
Do same steps as in Test1 but now run the program with `-p`: `./connect_test -p ./server.socket`. Notice now how nicely the client reconnects when the server is brought back. Another notable thing is that the uring connect says `Connection refused` only the 1st time and then for eternity `No such file or directory`. The old school connect says `Connection refused` as long as the server is down and then reconnects fine when the server is brought back.
```
Connection established
[3] Bytes read: 6
[3] Bytes read: 0
Connection closed
connect() failed: Connection refused
connect() failed: Connection refused
Connection established
```

### Test code
```
#include <stdio.h>
#include <stdlib.h>
#include <liburing.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include <poll.h>

enum
{
    CONNECT,
    READ,
};

typedef struct
{
    uint16_t type;
} conn_info_t;

static void add_read(struct io_uring *ring, int fd, char *buffer, uint32_t buffer_len)
{
    struct io_uring_sqe *sqe = io_uring_get_sqe(ring);
    io_uring_prep_read(sqe, fd, buffer, buffer_len, 0);

    conn_info_t *conn_i = malloc(sizeof(*conn_i));
    conn_i->type = READ;
    io_uring_sqe_set_data(sqe, conn_i);
}

static void add_connect(struct io_uring *ring, int *fd, const char *path)
{
    if (*fd != -1)
    {
        close(*fd);
    }

    if ((*fd = socket(AF_UNIX, SOCK_STREAM, 0)) < 0)
    {
        fprintf(stderr, "socket() failed: %s\n", strerror(errno));
        return;
    }

    struct io_uring_sqe *sqe = io_uring_get_sqe(ring);
    struct sockaddr_un sockaddr_un = { .sun_family = AF_UNIX };
    snprintf(sockaddr_un.sun_path, sizeof(sockaddr_un.sun_path), "%s", path);
    io_uring_prep_connect(sqe, *fd, (struct sockaddr *) &sockaddr_un, sizeof(sockaddr_un));

    conn_info_t *conn_i = malloc(sizeof(*conn_i));
    conn_i->type = CONNECT;
    io_uring_sqe_set_data(sqe, conn_i);
}

static bool myconnect(int *fd, const char *path)
{
    if (*fd != -1)
    {
        close(*fd);
    }

    if ((*fd = socket(AF_UNIX, SOCK_STREAM, 0)) < 0)
    {
        fprintf(stderr, "socket() failed: %s\n", strerror(errno));
        return false;
    }

    struct sockaddr_un sockaddr_un = { .sun_family = AF_UNIX };
    snprintf(sockaddr_un.sun_path, sizeof(sockaddr_un.sun_path), "%s", path);
    if (connect(*fd, (struct sockaddr *) &sockaddr_un, sizeof(sockaddr_un)) < 0)
    {
        fprintf(stderr, "connect() failed: %s\n", strerror(errno));
        return false;
    }
    fprintf(stderr, "Connection established\n");
    return true;
}


int main(int argc, char *argv[])
{
    if (argc != 3)
    {
        return EXIT_FAILURE;
    }

    char buffer[UINT16_MAX] = {};
    int fd = -1;
    if (!strcmp(argv[1], "-u"))
    {
        struct io_uring_params params = {};
        struct io_uring ring = {};

        if (io_uring_queue_init_params(5, &ring, &params) < 0)
        {
            fprintf(stderr, "io_uring_queue_init_params() failed: %s\n", strerror(errno));
            return EXIT_FAILURE;
        }

        add_connect(&ring, &fd, argv[2]);
        while (1)
        {
            io_uring_submit_and_wait(&ring, 1);
            u_int head;
            u_int count = 0;

            struct io_uring_cqe *cqe;
            io_uring_for_each_cqe(&ring, head, cqe)
            {
                ++count;
                conn_info_t *conn_i = io_uring_cqe_get_data(cqe);

                if (conn_i->type == CONNECT)
                {
                    if (cqe->res < 0)
                    {
                        fprintf(stderr, "connect() failed: %s\n", strerror(-cqe->res));
                        add_connect(&ring, &fd, argv[2]);
                        sleep(5);
                    }
                    else
                    {
                        fprintf(stderr, "Connection established\n");
                        add_read(&ring, fd, buffer, sizeof(buffer));
                    }
                }
                else if (conn_i->type == READ)
                {
                    int bytes_read = cqe->res;
                    if (cqe->res <= 0)
                    {
                        fprintf(stderr, "Connection closed: %d %s\n", cqe->res, strerror(-cqe->res));
                        add_connect(&ring, &fd, argv[2]);
                    }
                    else
                    {
                        fprintf(stderr, "[%d] Bytes read: %d\n", fd, bytes_read);
                        add_read(&ring, fd, buffer, sizeof(buffer));
                    }
                }

                free(conn_i);
            }
            io_uring_cq_advance(&ring, count);
        }
        io_uring_queue_exit(&ring);
    }
    else if (!strcmp(argv[1], "-p"))
    {
        while (!myconnect(&fd, argv[2]))
        {
            sleep(5);
        }

        struct pollfd pollfd = { .fd = fd, .events = POLLIN };
        while (1)
        {
            int poll_ret = poll(&pollfd, 1, 1000);
            if (poll_ret == -1)
            {
                fprintf(stderr, "poll() failed: %s\n", strerror(errno));
                close(fd);
                return EXIT_FAILURE;
            }

            if (pollfd.revents & POLLIN)
            {
                int bytes_read = read(fd, buffer, sizeof(buffer));
                if (bytes_read < 0)
                {
                    fprintf(stderr, "read() failed: %s\n", strerror(errno));
                }
                else
                {
                    fprintf(stderr, "[%d] Bytes read: %d\n", fd, bytes_read);
                }
            }

            if ((pollfd.revents & POLLHUP) || (pollfd.revents & POLLERR))
            {
                fprintf(stderr, "Connection closed\n");
                while (!myconnect(&fd, argv[2]))
                {
                    sleep(5);
                }
                pollfd.fd = fd;
            }
        }
    }
    else
    {
        return EXIT_FAILURE;
    }
}
```

**Comment by YoSTEALTH** [comment] 2022-01-25 00:26
I tried a simple connect and close to `/tmp/.X11-unix/X0`, no read/write and there was no problem reconnecting. `Linux 5.15.12`

**Comment by kosmas-valianos** [comment] 2022-01-25 13:52
Give it a try as per above 6 steps i.e. with removal of the unix domain socket while app is allive trying to reconnecting and then bringing up the socket with the same name

**Comment by pobrn** [comment] 2022-03-10 16:37
I can't reproduce this issue locally (5.16.12), but the problem may be related to the following:

> ```c
> io_uring_prep_connect(sqe, *fd, (struct sockaddr *) &sockaddr_un, sizeof(sockaddr_un));
> ```

`io_uring_prep_connect()` merely saves the pointer to the `struct sockaddr` object, and since that is on the stack, it is destroyed when `add_connect()` returns. It may be that the kernel sees an entirely different address from what you intended. I believe it is probably best to keep the address object alive until you get the cqe.

**Comment by pobrn** [comment] 2022-03-10 17:22
Thanks for the clarification. I wasn't sure, I didn't want to say something incorrect.

> Your test case should work if you do: [...]

Yes, it indeed does. But the original test code is still incorrect in my opinion since it submits an SQE with a dangling `addr` pointer.

**Comment by axboe** [comment] 2022-03-10 17:38
> Yes, it indeed does. But the original test code is still incorrect in my opinion since it submits an SQE with a dangling addr pointer.

Yes indeed it does, i'll close this one as the code is invalid.

What I said applies to any request type - the data passed in MUST be valid across submit. Once submit is done, you don't need to hang on to it until completion time.

**Closed by axboe** 2022-03-10 17:38 UTC

**Comment by kosmas-valianos** [comment] 2022-03-14 15:09
>test code is still incorrect in my opinion since it submits an SQE with a dangling addr

Indeed. Old habits die hard... `io_uring_prep_connect` uses of course the pointer in the "future" in contrast with the "normal" IO. By making the declaration globally the test works just fine.

```
#include <unistd.h>
#include <poll.h>

struct sockaddr_un sockaddr_un = { .sun_family = AF_UNIX };
```

>What I said applies to any request type - the data passed in MUST be valid across submit

That's a good clarification that came out of this :+1:

**Comment by axboe** [comment] 2022-03-14 15:11
> That's a good clarification that came out of this

I wonder how we can make this more prominent in the documentation, without having to put a section like that in all of the man pages that deal with request prep. But maybe that would indeed be the best way to do it, as then you'd certainly see it without having to read through pages of the overall documentation.

**Comment by kosmas-valianos** [comment] 2022-03-14 15:18
Maybe it can be a note in the submit instead of repeating it in all the request prep pages. That way you will certainly see it as if you want to use the library you have to read for the submit and also it will be no repetition
