### ISSUE TITLE
question about TCP socket connect and EINPROGRESS

### ISSUE THREAD

**Issue by romange** [axboe/liburing#841] opened 2023-04-11 03:40 UTC
AFAIK,  kernel with IORING_FEAT_FAST_POLL should not return EINPROGRESS error for IORING_OP_CONNECT calls.
And it never did until now, but recently we encounter cases where we receive EINPROGRESS (still not sure how to reproduce).

I've looked up for related issues and found this  https://github.com/axboe/liburing/issues/671 .
Could it change the iouring behavior and return EINPROGRESS in some cases for IORING_OP_CONNECT?

**Comment by axboe** [comment] 2023-04-11 04:04
Fixed in newer and stable kernels.

**Comment by royjacobson** [comment] 2023-04-11 09:16
A few more details - 

We're sending a `IORING_OP_CONNECT` on a non blocking socket and try to set a timeout with a previous `IORING_OP_LINK_TIMEOUT` request.
Then the connect request completes almost immediately with `EINPROGRESS`, but it only happens sometimes and under specific conditions that we're not sure how to reproduce.

Is this expected behavior? From looking at [tests/connect.cc](https://github.com/axboe/liburing/blob/4fed79510a189cc7997f6d04855ebf7fb66cc323/test/connect.c#L159) it looks like it might be, but we're not sure why we're seeing this only now and why.

**Comment by romange** [comment] 2023-04-11 09:26
I think, the connect test has been written before iouring has implemented
the fast_poll feature that handles io polling on behalf of a user app. So,
this code path should only be triggered for older kernels before 5.7

**Closed** 2023-04-11 12:16 UTC
