### ISSUE TITLE
How to read/write large files

### ISSUE THREAD

**Issue by aosterthun** [axboe/liburing#403] opened 2021-08-09 08:45 UTC
Hello there,

I'm currently trying to familiarize myself with liburing. I've started by implementing some basic examples to get used to the library and got stuck while trying to write to file. I'm basically looping over 4kB buffers and writing them to a file. I noticed that my file wasn't getting larger than 2.1 GB regardless of the number of 4kB blocks I have written. I figured out that I can not really write or read bigger files because the offset parameter in their prepare calls is limited to a `long` which limits the maximum offset to `2147483647 bytes` which matches the 2.1 GB file size noticed earlier. 

I found #29 which seems to cover the same problem, but doesn't really provide a solution. I would also expect `off_t` to be at least an `unsigned long` to support the full 32 bit. 

Generally the resulting question is: How can I work with larger files using the liburing interface. 

Thanks in advance, and if I left out some important information, just inform me about that, I will try to add them as soon as possible.

**Comment by metze-samba** [comment] 2021-08-09 09:23
The low level io_uring_prep_rw() takes __u64 offset, see
https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L214

Regarding 32bit platforms, -D_FILE_OFFSET_BITS=64
typically cause 'off_t' to be off64_t. So the problem is not io_uring specific,
also the pwrite() call has the same limitation unless off_t the same as off64_t.

**Comment by aosterthun** [comment] 2021-08-09 09:38
So the workaround is to use the io_uring function to prepare the io operation instead of the liburing provided function? That is probably fine for now, but I feel like this should at some point be addressed in liburing.

**Comment by metze-samba** [comment] 2021-08-09 09:42
I think you want to use -D_FILE_OFFSET_BITS=64 or '#define _FILE_OFFSET_BITS 64' before any includes,
then I guess io_uring_prep_write(), io_uring_prep_write_fixed() and io_uring_prep_writev() will pass down
the 64bit offset.

**Comment by aosterthun** [comment] 2021-08-09 10:29
I do not see a change in behaviour when I use the `#define _FILE_OFFSET_BITS 64` at the top of my file. 

```
submit idx: 524283 at: 2147463168
submit idx: 524284 at: 2147467264
submit idx: 524285 at: 2147471360
submit idx: 524286 at: 2147475456
submit idx: 524287 at: 2147479552
submit idx: 524288 at: -2147483648
submit idx: 524289 at: -2147479552
submit idx: 524290 at: -2147475456
submit idx: 524291 at: -2147471360
```

Also looking into both sys as well as bits `types.h` files suggests to me that `off64_t` is also a long for some reason. It should be `__u64` as in `io_uring_prep_rw` which would be an `unsigned long long`.

**Comment by YoSTEALTH** [comment] 2021-08-09 20:40
In my 64bit system `offset` -> `off_t` -> `int64_t` -> `+` or `-` `9223372036854775807` bytes.

@aosterthun 
It would have to be `signed` since reading/writing from `offset` `-123` (and such) is valid.

@axboe @isilence
On a 32bit system you could say `4GB` is the limit data can be stored into RAM. Not sure this should apply for `offset` of a file though! You should still be able to read/write TB+ file-size on a 32bit system.

**Comment by axboe** [comment] 2021-08-09 20:47
Pushed out a fix for this, please test and see if that works for you.

**Closed** 2021-08-09 20:47 UTC

**Comment by axboe** [comment] 2021-08-09 20:51
Note that off_t really should be 64-bit, if not then you're likely to run into issues anyway... The liburing changes just makes sure that we are not the problem, at least.

**Comment by YoSTEALTH** [comment] 2021-08-09 20:53
@axboe it would have to be `__s64`, no?

**Comment by axboe** [comment] 2021-08-09 20:55
For pure posix, yes they are signed. Don't think it matters here, we're passing it in as unsigned 64-bit anyway in the sqe, it'll get converted to signed in the kernel.

**Comment by YoSTEALTH** [comment] 2021-08-09 20:57
> For pure posix, yes they are signed. Don't think it matters here, we're passing it in as unsigned 64-bit anyway in the sqe, it'll get converted to signed in the kernel.

I see, thanks for clarifying and the fix :)

**Comment by aosterthun** [comment] 2021-08-10 08:06
Thanks for the quick fix.
