### ISSUE TITLE
commands failing with EINVAL on 5.4.58 kernel version

### ISSUE THREAD

**Issue by sumeetb25** [axboe/liburing#223] opened 2020-10-06 18:58 UTC
I built and ran `examples/io_uring-test` from liburing repository and run into the following error:

```
sudo ./io_uring-test /dev/nvme3n1

ret=-22, wanted 4096
Submitted=4, completed=1
```

Following is my kernel version on an ec2 instance. `5.4.58-32.125.amzn2.x86_64`

The kernel seems to have io_uring built into it.
```
 grep io_uring_enter /proc/kallsyms
0000000000000000 T __ia32_sys_io_uring_enter
0000000000000000 T __x64_sys_io_uring_enter
0000000000000000 d event_exit__io_uring_enter
0000000000000000 d event_enter__io_uring_enter
0000000000000000 d __syscall_meta__io_uring_enter
0000000000000000 d args__io_uring_enter
0000000000000000 d types__io_uring_enter
0000000000000000 t __event_exit__io_uring_enter
0000000000000000 t __event_enter__io_uring_enter
0000000000000000 t __p_syscall_meta__io_uring_enter
0000000000000000 t _eil_addr___ia32_sys_io_uring_enter
0000000000000000 t _eil_addr___x64_sys_io_uring_enter
```

The same program works fine on an ec2 instance with slightly older release. `5.4.46-23.77.amzn2.x86_64`

I'd appreciate if there are any pointers on why this occurs or directions on how to debug to get to an RCA,

**Comment by axboe** [comment] 2020-10-06 19:38
That test app doesn't work on block devices, it's only by luck if sb.st_size happens to align with the stars. If you run it on eg COPYING in that directory, it should work.

**Comment by sumeetb25** [comment] 2020-10-06 21:12
Thanks Jens for that response. I created a file and tried to run it on a file. Unfortunately that failed too.

**Comment by axboe** [comment] 2020-10-06 21:16
can you read that file with O_DIRECT? Try with:

```
dd if=file of=/dev/null bs=4k count=4 iflag=direct
```

on where ```file``` is the file you used for the test. If yes, then that sounds very strange.

**Comment by sumeetb25** [comment] 2020-10-06 21:34
Yeah dd worked fine.

```
[ec2-user@ip-10-0-60-92 ~]$ ls -la abc 
-rw-rw-r-- 1 ec2-user ec2-user 95095 Oct  6 21:30 abc

[ec2-user@ip-10-0-60-92 ~]$ dd if=abc of=/dev/null bs=4k count=4 iflag=direct
4+0 records in
4+0 records out
16384 bytes (16 kB) copied, 0.00122663 s, 13.4 MB/s

[ec2-user@ip-10-0-60-92 ~]$ ./io_uring-test abc
ret=-22, wanted 4096
Submitted=4, completed=1

```

**Comment by axboe** [comment] 2020-10-06 21:46
That's pretty puzzling. Is this:

5.4.58-32.125.amzn2.x86_64

stock 5.4.58 stable, or does it have amazon changes?

**Comment by axboe** [comment] 2020-10-06 21:48
I'd also update liburing just in case, your sha is pretty old. Would be a good data point.

**Comment by sumeetb25** [comment] 2020-10-06 21:55
> That's pretty puzzling. Is this:
> 
> 5.4.58-32.125.amzn2.x86_64
> 
> stock 5.4.58 stable, or does it have amazon changes?

I did the following steps from my ec2 instance to update to 5.4 

```
sudo amazon-linux-extras enable kernel-ng
yum check-update kernel
sudo /usr/bin/yum update -y 
sudo reboot
```

**Comment by axboe** [comment] 2020-10-06 21:59
Noted, doesn't really help me though, I have no idea if you're running some amazon special of if it's 5.4-stable stock (or at least close to)...

**Comment by sumeetb25** [comment] 2020-10-06 22:06
> I'd also update liburing just in case, your sha is pretty old. Would be a good data point.

I updated liburing to top of master (295d711a78833299c0b945ef8c67fb1aef09c68a) and saw the following outputs:

```
[ec2-user@ip-10-0-60-92 ~]$ ./io_uring-test abc
ret=0, wanted 4096
Submitted=4, completed=1, bytes=0

[ec2-user@ip-10-0-60-92 ~]$ ./io_uring-test abc
ret=-22, wanted 4096
Submitted=4, completed=1, bytes=18446744073709551594

[ec2-user@ip-10-0-60-92 ~]$ ./io_uring-test abc
ret=-22, wanted 4096
Submitted=4, completed=1, bytes=18446744073709551594

[ec2-user@ip-10-0-60-92 ~]$ ./io_uring-test abc
ret=0, wanted 4096
Submitted=4, completed=1, bytes=0

```

**Comment by sumeetb25** [comment] 2020-10-06 22:17
> Noted, doesn't really help me though, I have no idea if you're running some amazon special of if it's 5.4-stable stock (or at least close to)...

I'll update kernel version on my instance to stock 5.4.58 stable and see whether I can repro it.

**Comment by sumeetb25** [comment] 2020-10-07 01:58
> > Noted, doesn't really help me though, I have no idea if you're running some amazon special of if it's 5.4-stable stock (or at least close to)...
> 
> I'll update kernel version on my instance to stock 5.4.58 stable and see whether I can repro it.

I updated kernel version on my instance to be stock 5.4.58 stable (git commit id - cad17feaf0d05e60f7fe3c29908f9e2d07fbb7ee) and it still does not seem to work.

```
[ec2-user@ip-10-0-52-34 ~]$ uname -a
Linux ip-10-0-52-34.ec2.internal 5.4.58 #1 SMP Wed Oct 7 01:40:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[ec2-user@ip-10-0-52-34 ~]$ dd if=abc of=/dev/null bs=4k count=4 iflag=direct
4+0 records in
4+0 records out
16384 bytes (16 kB) copied, 0.00161596 s, 10.1 MB/s

[ec2-user@ip-10-0-52-34 ~]$ ./io_uring-test abc
ret=0, wanted 4096
Submitted=4, completed=1, bytes=0

[ec2-user@ip-10-0-52-34 ~]$ ./io_uring-test abc
ret=0, wanted 4096
Submitted=4, completed=1, bytes=0

[ec2-user@ip-10-0-52-34 ~]$ ./io_uring-test abc
ret=0, wanted 4096
Submitted=4, completed=1, bytes=0

[ec2-user@ip-10-0-52-34 ~]$ ./io_uring-test abc
ret=0, wanted 4096
Submitted=4, completed=1, bytes=0
```

**Comment by sumeetb25** [comment] 2020-10-07 17:04
Jens any pointers on what the issue might be? If you can point me to a suitable place to start digging into I'd be glad to look into it too.

**Comment by axboe** [comment] 2020-10-07 17:09
I honestly am pretty blank right now, it makes very little sense to me. Just queued up a few patches for 5.4-stable, maybe (just maybe) they will help out your case. But I can't reproduce any of this, and the changes between the working and failing version shouldn't have any impact at all.

If you're up for compiling your own kernel, then we can add some debug stuff to try and pin point what is going wrong.

**Comment by sumeetb25** [comment] 2020-10-07 17:16
Yeah I am compiling my own kernel and can gladly add debug stuff to it

**Comment by axboe** [comment] 2020-10-07 17:20
Great - let me prepare a debug patch you can add, then we can take it from there.

**Comment by axboe** [comment] 2020-10-07 17:30
Actually, maybe you can try the posted fixes first - you can download them bundled into one here: https://kernel.dk/iou.patch

**Comment by sumeetb25** [comment] 2020-10-07 17:31
Ack. Working on building kernel from that patch.

**Comment by sumeetb25** [comment] 2020-10-07 17:47
> Actually, maybe you can try the posted fixes first - you can download them bundled into one here: https://kernel.dk/iou.patch

Hunk 6 of that patch does not apply cleanly. It seems there is difference in expectation for io_add_to_prev_work function.

Here is what I have in fs/io_uring.c as checked out from tag 5.4.58

```
static bool io_add_to_prev_work(struct async_list *list, struct io_kiocb *req)
{
        bool ret;

        if (!list)
                return false;
        if (!(req->flags & REQ_F_SEQ_PREV))
                return false;
        if (!atomic_read(&list->cnt))
                return false;

        ret = true;
        spin_lock(&list->lock);
        list_add_tail(&req->list, &list->list);
        /*
         * Ensure we see a simultaneous modification from io_sq_wq_submit_work()
         */
        smp_mb();
        if (!atomic_read(&list->cnt)) {
                list_del_init(&req->list);
                ret = false;
        }
        spin_unlock(&list->lock);
        return ret;
}

```
Is there another patch series that I need to apply before the one you shared?

**Comment by axboe** [comment] 2020-10-07 17:49
You want to be on the latest 5.4-stable before applying that patch series.

**Comment by sumeetb25** [comment] 2020-10-07 17:53
> You want to be on the latest 5.4-stable before applying that patch series.

Ack.

**Comment by sumeetb25** [comment] 2020-10-07 18:20
It works fine with the patch applied to 5.4.70+ (commit id: d22f99d235e13356521b374410a6ee24f50b65e6)

```
[ec2-user@ip-10-0-52-34 ~]$ uname -a
Linux ip-10-0-52-34.ec2.internal 5.4.70+ #2 SMP Wed Oct 7 18:09:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[ec2-user@ip-10-0-52-34 ~]$ ./io_uring-test abc
Submitted=4, completed=4, bytes=16384

[ec2-user@ip-10-0-52-34 ~]$ 
```

It is still a mystery why it fails with 5.4.58

**Comment by axboe** [comment] 2020-10-07 18:22
Very much a mystery, must be a side effect of the issues being fixed with the latest series. In any case, the good news is that the patches will be in 5.4.71, so at least it'll be an interim thing for you. Would still love to figure this out, but for the life of me, I cannot reproduce anything bad locally...

**Comment by sumeetb25** [comment] 2020-10-07 18:24
> Very much a mystery, must be a side effect of the issues being fixed with the latest series. In any case, the good news is that the patches will be in 5.4.71, so at least it'll be an interim thing for you. Would still love to figure this out, but for the life of me, I cannot reproduce anything bad locally...

Yeah I'd love to figure this out too. Want to share a debug patch with me that I can apply to 5.4.58?

**Comment by axboe** [comment] 2020-10-07 18:30
I'd just try 5.4.70 stock first, without the patches. If that still fails, then I don't think we need to look any further, as it's a side effect of a previous patch that got fixed up by the new series.

**Comment by sumeetb25** [comment] 2020-10-07 19:48
It worked fine with 5.4.70 stock (git commit id - d22f99d235e13356521b374410a6ee24f50b65e6)

```
[ec2-user@ip-10-0-56-76 ~]$ uname -a
Linux ip-10-0-56-76.ec2.internal 5.4.70 #2 SMP Wed Oct 7 19:38:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[ec2-user@ip-10-0-56-76 ~]$ ll abc 
-rw-rw-r-- 1 ec2-user ec2-user 1170117 Oct  7 19:46 abc

[ec2-user@ip-10-0-56-76 ~]$ ./io_uring-test abc
Submitted=4, completed=4
```

It seems we have some regression in 5.4.58 that gets fixed in later releases.

**Comment by axboe** [comment] 2020-10-07 19:55
OK, I see what it is now, this is the fix:

```
commit a02df82a59c3dbc7bf657efca82e1641ca472eb4
Author: Liu Yong <pkfxxxing@gmail.com>
Date:   Wed Aug 12 23:56:44 2020 -0700

    fs/io_uring.c: Fix uninitialized variable is referenced in io_submit_sqe
```

which is in 5.4.59, so it just missed 5.4.58 and hence caused your problem.

**Comment by axboe** [comment] 2020-10-07 19:56
Just checked, and the issue only exists in that very version - 5.4.57 doesn't have it, and 5.4.59 has the fix for the 5.4.58 issue. So you just got very unlucky!

**Comment by sumeetb25** [comment] 2020-10-07 19:57
Huh. Can you please talk a little more on what the issue was?

**Comment by sumeetb25** [comment] 2020-10-07 20:10
> Huh. Can you please talk a little more on what the issue was?

Ah. I just saw your comment. That makes sense. Thanks Jens for your help.

**Closed** 2020-10-07 20:11 UTC
