### ISSUE TITLE
In sqpoll mode, submit returns -EOWNERDEAD

### ISSUE THREAD

**Issue by quininer** [axboe/liburing#413] opened 2021-08-14 11:38 UTC
kernel: 5.13.9-arch1-1

This looks like a bug because it does not match the intention described by commit. https://github.com/torvalds/linux/commit/d9d05217cb6990b9a56e13b56e7a1b71e2551f6c

reproduce code:
```c
int main(int argc, char *argv[])
{
	struct io_uring_sqe *sqe;
	struct io_uring ring;
	int ret;

	if (argc > 1)
		return 0;

	struct io_uring_params p = {};
	p.flags = IORING_SETUP_SQPOLL;
	p.sq_thread_idle = 100;

	ret = io_uring_queue_init_params(1, &ring, &p);
	if (ret) {
		fprintf(stderr, "child: ring setup failed: %d\n", ret);
		return 1;
	}

	ret = io_uring_submit(&ring);
	if (ret <= 0) {
		fprintf(stderr, "child: sqe submit failed: %d\n", ret);
		return 1;
	}

	return 0;
}
```
output:
```
child: sqe submit failed: -130
```

**Comment by axboe** [comment] 2021-08-14 14:44
Heh, I think it's a weird case with the ring being empty. We assign ret = -EOWNERDEAD early, then go through the submit and wait logic. But you end up with submitted == 0, and ret never being set to something else. That can cause a spurious EOWNERDEAD return, just because we did nothing else.

This should fix it:

```
diff --git a/fs/io_uring.c b/fs/io_uring.c
index 32f3df13a812..da4c716a6844 100644
--- a/fs/io_uring.c
+++ b/fs/io_uring.c
@@ -9352,8 +9352,8 @@ SYSCALL_DEFINE6(io_uring_enter, unsigned int, fd, u32, to_submit,
 	if (ctx->flags & IORING_SETUP_SQPOLL) {
 		io_cqring_overflow_flush(ctx, false);
 
-		ret = -EOWNERDEAD;
 		if (unlikely(ctx->sq_data->thread == NULL)) {
+			ret = -EOWNERDEAD;
 			goto out;
 		}
 		if (flags & IORING_ENTER_SQ_WAKEUP)
```

**Comment by axboe** [comment] 2021-08-14 15:05
Added a test case and committing a kernel fix for this one now. It'll bubble back into -stable as well.

Pretty silly...

**Comment by axboe** [comment] 2021-08-14 15:08
@quininer If you want to get attributed with a Reported-by tag, please give me your full name an email. So far the commit looks like this:

https://git.kernel.dk/cgit/linux-block/commit/?h=io_uring-5.14&id=6529cb63914f75d7ec4ba7699d1ab48859230c0b

but I can amend it and add the Reported-by tag.

**Comment by axboe** [comment] 2021-08-14 15:10
And regression test:

https://git.kernel.dk/cgit/liburing/commit/?id=82bbab585ed8fdef5c65ec826e5fcbfa9f370a25

**Comment by quininer** [comment] 2021-08-14 15:14
> @quininer If you want to get attributed with a Reported-by tag, please give me your full name an email.

I don't mind this, maybe @Sherlock-Holo will want it.

**Comment by Sherlock-Holo** [comment] 2021-08-14 17:03
the name and email is Sherlock Holo sherlockya@gmail.com

**Comment by axboe** [comment] 2021-08-14 18:35
@Sherlock-Holo Amended and pushed out a new head.

I'm going to close this one, thanks for reporting.

**Closed by axboe** 2021-08-14 18:35 UTC
