### ISSUE TITLE
Feature: io_uring_prep_getdents

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#139] opened 2020-05-26 22:39 UTC
Could `io_uring_prep_getdents` https://linux.die.net/man/2/getdents64 be added to `liburing`?

With `io_uring` crazy fast async buffered reads support now I wonder how this feature will be effected :)

Thank you

**Comment by axboe** [comment] 2020-05-29 17:51
Closing as a dupe of #111

**Closed by axboe** 2020-05-29 17:51 UTC
