### ISSUE TITLE
linking open - write (or read) - close

### ISSUE THREAD

**Issue by realwakka** [axboe/liburing#1234] opened 2024-09-18 00:50 UTC
It would be useful if there is write or read options that use fd from hard linked prior open operation. The same goes on close operation.
I think it could be used for simple tasks like `cat`, open, read and close. This feature can do `cat` task for just oneshot without switching userspace.

**Comment by axboe** [comment] 2024-09-18 06:39
You can do that with fixed/registered files - then you control (or know) which fd value you will get, which you can then use in the followup read/write and close.

**Comment by axboe** [comment] 2024-09-18 06:47
Closing - please open future question like this as a discussion, as it's not a bug that needs resolving.

**Closed by axboe** 2024-09-18 06:47 UTC
