### ISSUE TITLE
Ignore results from some operations, e.g. `close`.

### ISSUE THREAD

**Issue by ioquatix** [axboe/liburing#376] opened 2021-07-12 23:05 UTC
We don't care about the results of some operations. An example of this would be `close` - some others might include `flush` etc. Often we don't care about the results. We just want to batch them and process them as quickly as possible. 

It would be nice if there was some way to mark a SQ entry as "Please do this thing but don't bother telling me about it." This avoids filling the CQ with entries we don't care about. Maybe we can implicitly do this when `user_data` is `0`/`NULL`? (probably unsafe/incompatible). Another option is a per SQ flag.

Maybe this already exists and I don't know about it.

**Comment by ioquatix** [comment] 2021-07-12 23:42
I'd like to discuss the performance implications of this. I'm currently experimenting punting `close` operations to `io_uring`.

The code looks like this:

```c
static const int ASYNC_CLOSE = 0;

VALUE Event_Backend_URing_io_close(VALUE self, VALUE io) {
        struct Event_Backend_URing *data = NULL;
        TypedData_Get_Struct(self, struct Event_Backend_URing, &Event_Backend_URing_Type, data);

        int descriptor = Event_Backend_io_descriptor(io);

        if (ASYNC_CLOSE) {
                struct io_uring_sqe *sqe = io_get_sqe(data);
                assert(sqe);

                io_uring_prep_close(sqe, descriptor);
                io_uring_sqe_set_data(sqe, NULL);
                if (ASYNC_CLOSE == 1)
                        io_uring_submit_now(data);
                else if (ASYNC_CLOSE == 2)
                        io_uring_submit_pending(data);
        } else {
                close(descriptor);
        }

        // We don't wait for the result of close since it has no use in pratice:
        return Qtrue;
}
```

Here are the results:

#### ASYNC_CLOSE = 0

```
Running 10s test @ http://localhost:9090
  4 threads and 16 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   305.32us  218.20us  13.30ms   95.65%
    Req/Sec    12.12k     1.54k   16.74k    55.83%
  486152 requests in 10.10s, 21.33MB read
Requests/sec:  48136.38
Transfer/sec:      2.11MB

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ------------------
 29.90    0.051782           5     10000           write
 25.62    0.044376           4     10243           close
 21.89    0.037907           3     10003         3 accept4
 17.26    0.029890           2     10322         8 read
  4.73    0.008194           3      2082           mprotect
  0.17    0.000292           1       201           mmap
  0.10    0.000174           1        88           munmap
  0.06    0.000102           8        12         1 io_uring_enter
```

#### ASYNC_CLOSE = 1

```
Running 10s test @ http://localhost:9090
  4 threads and 16 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   347.38us  197.85us  10.35ms   95.09%
    Req/Sec    10.71k     1.24k   13.66k    61.39%
  430436 requests in 10.10s, 18.88MB read
Requests/sec:  42619.47
Transfer/sec:      1.87MB

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ------------------
 27.88    0.046324           4     10000           write
 27.46    0.045627           4     10165         1 io_uring_enter
 21.01    0.034910           3     10002         2 accept4
 17.66    0.029342           2     10475       161 read
  4.65    0.007727           3      2082           mprotect
  0.67    0.001111         555         2           bind
  0.40    0.000665         665         1           listen
  0.10    0.000167           0       204           mmap
  0.10    0.000164           1        92           munmap
  0.06    0.000096           1        54           brk
  0.00    0.000000           0       243           close
```

#### ASYNC_CLOSE = 2

```
Running 10s test @ http://localhost:9090
  4 threads and 16 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   340.41us  138.34us   6.01ms   92.12%
    Req/Sec    10.80k     1.23k   13.80k    54.70%
  434256 requests in 10.10s, 19.05MB read
Requests/sec:  42996.25
Transfer/sec:      1.89MB

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ------------------
 27.27    0.038557           3     10000           write
 27.16    0.038401           3     10003           io_uring_enter
 20.43    0.028888           2     10003         3 accept4
 17.47    0.024696           2     10494       180 read
  4.26    0.006027           2      2082           mprotect
  0.61    0.000860           1       551       551 readlink
  0.61    0.000856           1       497       260 openat
  0.49    0.000696         348         2           bind
  0.35    0.000489           1       394         9 newfstatat
  0.24    0.000346           1       205           mmap
  0.22    0.000314           1       243           close
```

#### ASYNC_CLOSE = 3

In this mode, submission of the queue only occurs when some other operation is submitted. Because of this, it's very easy to overload the SQ and CQ, and this is where I think an option to ignore CQE entries would be really great. As you can see from `strace`, the `close` system call becomes batched, 100,000x `close` calls -> 348x `io_uring_enter`.

```
Running 10s test @ http://localhost:9090
  4 threads and 16 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   815.05us    1.30ms  18.71ms   88.51%
    Req/Sec     4.33k     4.71k   13.65k    70.43%
  172063 requests in 10.09s, 7.55MB read
Requests/sec:  17046.16
Transfer/sec:    765.75KB

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ------------------
 34.17    0.034045           3     10089           write
 25.53    0.025442           2     10092         3 accept4
 21.31    0.021236           1     10669       266 read
 12.74    0.012697          36       348           io_uring_enter
  4.89    0.004877           2      2082           mprotect
  0.39    0.000392           0       394         9 newfstatat
  0.23    0.000231           0       497       260 openat
  0.19    0.000186           2        91           munmap
  0.18    0.000180           0       204           mmap
  0.10    0.000104           0       243           close
```

**Comment by ioquatix** [comment] 2021-07-12 23:46
In addition to the results above, I'm a little bit confused as to why `ASYNC_CLOSE = 0` is faster by about 15%. Well, maybe it makes sense because `io_uring` has some overhead in that it's essentially doing `close` on the kernel side + reading from the SQ followed by writing to the CQ. Is that logical?

We don't always know when `close` will be slow so it's preferable to have it asynchronous, but the cost here is pretty high.

**Comment by YoSTEALTH** [comment] 2021-07-13 14:52
`io_uring_prep_close` is probably there for convenience vs for speed. `IORING_OP_CLOSE` says it calls `close(2)` under the hood anyways.

Maybe you can see benefit of close on cases where you link it with something else! e.g:

``` Python
io_uring_prep_send(sqe, ...)
sqe |= IOSQE_IO_LINK
io_uring_prep_close(..., fd)
```

**Comment by ioquatix** [comment] 2021-07-13 21:05
Unfortunately it's very hard for us to leverage linked `OP_CLOSE` in a dynamic language unless we track all operations being performed on a given file descriptor and try to batch them with linking, or introduce some new methods like `send_and_close`

**Comment by isilence** [comment] 2021-07-14 13:59
related to / dup of https://github.com/axboe/liburing/issues/321

**Comment by YoSTEALTH** [comment] 2021-07-19 01:10
This is the result I am getting `close` vs `io_uring_prep_close`

# using `close`
Transaction rate:   4405.29 trans/sec
Transaction rate:   4347.83 trans/sec
Transaction rate:   4405.29 trans/sec

# using `io_uring_prep_close`
Transaction rate:   4784.69 trans/sec
Transaction rate:   4444.44 trans/sec
Transaction rate:   4807.69 trans/sec

**Comment by ioquatix** [comment] 2021-07-19 07:16
I think it depends on whether you've got pending data or not, in our case, `close` is hitting a bunch of TCP flushing.

**Comment by axboe** [comment] 2021-09-16 02:58
I'm going to close this one as a dupe of 321. That work will most likely land in 5.16.

**Closed by axboe** 2021-09-16 02:58 UTC

**Comment by ioquatix** [comment] 2021-09-16 04:21
@axboe thanks for all your effort and communication.
