### ISSUE TITLE
liburing/io_uring not working in kernel version 5.9+ on Ubuntu

### ISSUE THREAD

**Issue by aliabbas299792** [axboe/liburing#244] opened 2020-12-01 18:46 UTC
I've come across a weird issue where io_uring/liburing doesn't seem to work on kernel versions 5.9+.
I tried 3 different kernel versions: v5.8.18, v5.9.0, v5.9.10, and it only worked on v5.8.18.

These are the steps I took to reproduce this (in place of [VERSION] I put v5.8.18, v5.9.0 and v5.9.10 in the 3 runs):
```
apt update && \
apt install -y build-essential gcc make git && \
wget https://raw.githubusercontent.com/pimlie/ubuntu-mainline-kernel.sh/master/ubuntu-mainline-kernel.sh && \
chmod +x ubuntu-mainline-kernel.sh && \
mv ubuntu-mainline-kernel.sh /usr/local/bin/ && \
ubuntu-mainline-kernel.sh -i [VERSION] && \
git clone https://github.com/axboe/liburing.git && \
cd liburing && make -j && \
make install && cd .. && \
wget https://raw.githubusercontent.com/shuveb/io_uring-by-example/master/05_webserver_liburing/main.c
```
The `main.c` file downloaded above is an example io_uring web server server from: https://github.com/shuveb/io_uring-by-example

After this, I rebooted, then tried to compile and run:
```
gcc main.c -o server -luring && \
echo "done" && \
./server
```
Connecting to the server via [IP]:8000 in a browser (where IP is the server IP or whatever), should have resulted in a 404 like this:
![image](https://user-images.githubusercontent.com/22846134/100782837-e582cc00-3404-11eb-85e8-05ce8c85692f.png)
But instead results in a page just infinitely loading, and when you close the tab/stop it from loading, only then it prints a 404 message to the command line (on kernel versions v5.9.0 and v5.9.10).

`uname -a` from all 3 runs:
v5.8.18:
`Linux ubuntu-2gb-hel1-3 5.8.18-050818-generic #202011011237 SMP Sun Nov 1 12:40:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
v5.9.0:
`Linux ubuntu-2gb-hel1-2 5.9.0-050900-generic #202010112230 SMP Sun Oct 11 22:34:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
v5.9.10:
`Linux ubuntu-2gb-hel1-1 5.9.10-050910-generic #202011221708 SMP Sun Nov 22 18:07:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

These were all run on fresh installs as well, what could be the issue here?

**Comment by isilence** [comment] 2020-12-04 14:17
CC @shuveb, that may be io_uring-by-example problem (or not).
Anyway would be great to get anything more particular, like logs or what errors io_uring returns

**Comment by aliabbas299792** [comment] 2020-12-05 23:47
From what I can tell there are no logs or errors generated, so I'm not sure what else I can post

**Comment by ben0x539** [comment] 2021-01-14 20:15
I'm running into an issue with just io_uring, without liburing, on a 5.9 and 5.10 kernel, at least, where the remote side doing a single, short write to a tcp socket isn't enough to make a read request complete. This breaks the tiny http server we're playing around with, but also seems to break in a minimal interaction:

1) get a tcp socket from accept/connect, via io_uring or by old-style calls
2) the other side writes like five bytes to the socket
3) put a read request for like 128 bytes into the buffer, call io_uring_enter to_submit=1 min_complete=0
   (a this point the data from the remote side becomes visible in the buffer but there is no completion event)
4) call io_uring_enter to_submit=0 min_complete=1 ENTER_GETEVENTS - this blocks indefinitely, until the other side uses shutdown() or closes the socket.

The ordering of 2 vs 3 doesn't seem to matter. The other side could be `curl` making an http request (itself then blocking indefinitely after sending the headers) or just some `echo | nc`. I only have a [somewhat gross test program written in rust](https://gist.github.com/ben0x539/92311d36fb48d652ff411451d0c65db2) b/c that's what I reduced this from.

It's likely I'm holding it wrong, but since a) strace shows the syscalls i expect and b) a coworker can't reproduce this with an older kernel, this may be the same regression?

**Comment by isilence** [comment] 2021-01-15 05:10
>     3. put a read request for like 128 bytes into the buffer, call io_uring_enter to_submit=1 min_complete=0
>        (a this point the data from the remote side becomes visible in the buffer but there is no completion event)

Since not too long ago io_uring hides short reads from users by internally resubmitting IO, like
```C
while (size)
    size -= kernel_read(size, ...);
```

It looks like it's what you see. Can you confirm that you use read requests but not recv?

**Comment by ben0x539** [comment] 2021-01-15 21:49
Yes, I'm using read, not recv. Turns out with recv this behaves as I expected! Thanks so much, I'd never have figured this out, I've always assumed recv was the same as read except that you can pass flags.

Does this depend on the kind of file descriptor I'm reading from? I think when I was reading from stdin instead of a socket I did see the short reads.

**Comment by isilence** [comment] 2021-01-16 00:43
> Yes, I'm using read, not recv. Turns out with recv this behaves as I expected! Thanks so much, I'd never have figured this out, I've always assumed recv was the same as read except that you can pass flags.

well, it's a io_uring specific behaviour, read(2) and et al. don't do that.

> 
> Does this depend on the kind of file descriptor I'm reading from? I think when I was reading from stdin instead of a socket I did see the short reads.

It should not.
There was some specific bits that can indirectly slightly shift the observable behaviour, but that's not for sure

**Comment by shuveb** [comment] 2021-01-16 09:17
> CC @shuveb, that may be io_uring-by-example problem (or not).
> Anyway would be great to get anything more particular, like logs or what errors io_uring returns

Thanks for tagging me here. I've checked with Ubuntu 20.10 running kernel version 5.8.38-generic and the web server example seems to work well, displaying the web page as expected.

**Comment by isilence** [comment] 2021-01-18 23:44
yeah, the original report says as well (for v5.8.18), it's probably as per discussion with @ben0x539, recv vs read differences because of internal retrying of short reads.

**Comment by isilence** [comment] 2021-01-21 17:13
Jens queued a fix, @ben0x539, @aliabbas299792  any chance you can build and test it?

Also, if you can provide yours emails we will add reported-by tags to the commit (if wouldn't be too late).

**Comment by aliabbas299792** [comment] 2021-01-22 19:25
Hi, thanks for the comments here, great to find out why exactly that issue popped up

I've cloned the repo and tried `make oldconfig` followed by `make -j`, but make throws a whole bunch of errors, am I doing this wrong? Or should I just let it run? (Sorry this is the first time I've tried building something this large)

(My email is aliabbas.299792@gmail.com)

**Comment by isilence** [comment] 2021-01-22 21:46
> Hi, thanks for the comments here, great to find out why exactly that issue popped up
> 
> I've cloned the repo and tried `make oldconfig` followed by `make -j`, but make throws a whole bunch of errors, am I doing this wrong? Or should I just let it run? (Sorry this is the first time I've tried building something this large)

What your errors look like? E.g. you can paste it here

> 
> (My email is [aliabbas.299792@gmail.com](mailto:aliabbas.299792@gmail.com))

Thanks, may I ask your name/last name as well? It looks like
Reported-by: Pavel Begunkov <myemail@example.com>

**Comment by aliabbas299792** [comment] 2021-01-23 11:31
```
gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
  CC      fs/ext4/migrate.o
  CC      security/selinux/netport.o
gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
  CC      kernel/irq/matrix.o
make[3]: *** [scripts/Makefile.build:360: arch/x86/platform/efi/efi_stub_64.o] Error 137
make[3]: *** Deleting file 'arch/x86/platform/efi/efi_stub_64.o'
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:279: arch/x86/mm/maccess.o] Error 1
gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
  CC      kernel/time/timecounter.o
gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
  CC      kernel/trace/trace_kprobe.o
  CC      fs/ext4/mmp.o
  CC      mm/vmalloc.o
  CC      mm/page_alloc.o
gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[3]: *** [scripts/Makefile.build:279: arch/x86/kernel/cpu/topology.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC      arch/x86/kernel/msr.o
  CC      fs/ext4/indirect.o
  CC      kernel/trace/power-traces.o
  CC      fs/ioctl.o
  CC      security/keys/user_defined.o
make[1]: *** [scripts/Makefile.build:279: init/do_mounts_initrd.o] Error 1
make[1]: *** [scripts/Makefile.build:279: init/main.o] Error 1
make[1]: *** [scripts/Makefile.build:279: init/do_mounts.o] Error 1
  CC      fs/ext4/ioctl.o
gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
  CC      security/selinux/netnode.o
  CC      fs/nls/nls_utf8.o
make[3]: *** [scripts/Makefile.build:279: arch/x86/events/amd/uncore.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [scripts/Makefile.build:279: arch/x86/events/amd/ibs.o] Error 1
```
Errors of the sort above are what I'm getting a lot of, I'm not sure if it's just that the server I'm using doesn't have enough resources to build without getting these `terminated program` messages or if it's an actual error in how I'm building

And `Reported-by: Ali Abbas aliabbas.299792@gmail.com` (does that work?)

**Comment by axboe** [comment] 2021-01-23 16:29
A quick guess - you are _actually_ doing make -j, which basically turns into a fork bomb... This triggers the oom killer, and you get killed tasks while compiling. Try doing eg make -j8 - that will use 8 tasks for compiling. What's best depends on your system, for max speed I like to use -jN, where N == 2*NCPUS for that system.

**Comment by aliabbas299792** [comment] 2021-01-23 20:31
It finally finished building after a few hours (thanks - setting -j2 worked), and I tried rebooting into it, but it appears to get stuck at this point and doesn't progress further
![image](https://user-images.githubusercontent.com/22846134/105613242-78166a80-5db9-11eb-9186-fe0e9a1740dd.png)

I was correct in cloning via `git://git.kernel.dk/linux-block`, then switching to the branch `io_uring-5.11`, making the project, `make modules_install`, then `sudo make install`, then `sudo update-initramfs -c -k 5.11.0-rc1+` followed by `sudo update-grub` right?

I rebooted after that and it shows the screen I posted after a bit

**Comment by axboe** [comment] 2021-01-23 20:51
Installing a custom kernel can be a pain in the butt, if you haven't done it before. What you did looks correct, though... My process is generally, for ubuntu based distributions:

```
$ make
$ sudo make modules_install
$ sudo cp arch/x86/boot/bzImage /boot/vmlinuz-5.11.0-rc1+
$ sudo update-initramfs -c -k 5.11.0-rc1+
$ sudo update-grub2
```

which looks about the same, I believe make install puts the kernel image where it should be. So I guess that's a long winded way of saying what you did looks correct, not sure why it isn't fully booting for you... Any messages higher up?

**Comment by aliabbas299792** [comment] 2021-01-23 21:40
Just to be sure I went ahead and redid it by following your exact steps, and its still stuck. I may have missed something, but I believe that these are the only things possibly indicative of an error:
 - `Wrong EFI loader signature` towards the beginning
 - Towards the end `Freeing unused kernel image (initmem) memory: 1188K` and 2 others for (text/rodata gap) and `(rodata/data gap)`

I couldn't make out anything else which would possibly indicate any issues

**Comment by axboe** [comment] 2021-01-24 00:38
Usually when it stalls like that it's waiting for a mount point or device, which turns out to be missing from initramfs for whatever reason. So if you're game, you could try and ensure that any storage device (and filesystem) you are using is set to =y in the kernel .config file. Then repeat your make and the rest of the steps, try and boot that kernel.

**Comment by aliabbas299792** [comment] 2021-01-24 03:48
I attempted this, but I didn't get much further than a stuck bootscreen unfortunately, thank you for guiding me but I think this is as far as I get (it's a tad more difficult since, being a VPS, I'm not entirely sure about the hardware)

**Comment by axboe** [comment] 2021-01-24 04:09
Thanks for trying. I just reproduced and verified the fix, so hopefully the next -stable will have it for you and it'll work. I'm going to go ahead and close this one, please do re-test with the next 5.9-stable or 5.10-stable.

**Closed by axboe** 2021-01-24 04:09 UTC
