### ISSUE TITLE
Efficiently reset both submission and completion queues

### ISSUE THREAD

**Issue by emanuelpalm** [axboe/liburing#528] opened 2022-02-19 21:59 UTC
Is there a safe way to completely purge all entries from both the submission and completion queues without having to call `io_uring_queue_exit()`?

I need this for a termination procedure where I (1) purge all on-going activities, (2) execute a list of termination handlers (callback functions) that must be able to submit new SQEs and (3) wait for both the submission and completion queues to become empty. The actual procedure is more involved, but this is the gist of what I want this for. I want to avoid the overhead of having to call `io_uring_queue_exit()` and `io_uring_queue_init()` right after each other to reset the rings.

**Comment by axboe** [comment] 2022-02-20 00:07
Clearing the ring indexes would be trivial, the hard part is the internal state. You'd have to cancel everything, just like exit would do. Might actually not be a bad idea to provide a way to do that, as it would allow some targeted regression testing there as well. But that's the main one, ensuring that there's nothing running or pending in the kernel for that particular ring. Outside of that, in liburing it's just zeroing sq/cq head and tail.

The big question is how much faster it'd be at that point. Probably still slightly so, but probably not substantially.

**Comment by emanuelpalm** [comment] 2022-02-20 06:06
Is the only consequence of the kernel rings not being reset that new CQEs could arrive in the completion ring?

I guess I'll just call exit and then init again right afterwards then. If it would become a serious bottleneck I'll get back here.

**Comment by axboe** [comment] 2022-02-20 13:40
> Is the only consequence of the kernel rings not being reset that new CQEs could arrive in the completion ring?

Right, you could have pending requests that then complete at a later time, post the reset.

I'll close this one up, feel free to reopen as necessary.

**Closed by axboe** 2022-02-20 13:40 UTC

**Comment by tofes** [comment] 2022-04-14 07:04
This is probably the closest question to mine. I do not want to "reset" the submission queue, but I want to cancel all the requests on the `SQ`.  I tried something like below:
```
....
        int sqHead = *(sq->khead) - 1;
        int sqTail = *(sq->ktail) - 1;
        struct io_uring_sqe* currSqe = nullptr;
        unsigned long long* currAddr = nullptr;
        for (int i = sqHead; i >= 0 && i < sqTail; ++i)
        {
            currSqe = &sq->sqes[i];
            currAddr = &currSqe->user_data;
            io_uring_prep_cancel(currSqe, currAddr, 0);
            int ret = io_uring_submit(m_uring);
....
        }
```
I searched in liburing and did not find a function that does "cancel_all", am I missing something?
The problem is that after I close a socket fd to disconnect, io_uring doesn't automatically cancel all the existing submitted requests by that socket.

**Comment by axboe** [comment] 2022-04-14 17:53
@tofes Please file a new one for this, it's a different use case. I do think it's a valid use case and we should be able to make cancelation key off the file used.

**Comment by axboe** [comment] 2022-04-14 20:16
Did a quick implementation here:

https://git.kernel.dk/cgit/linux-block/log/?h=for-5.19/io_uring-cancel_fd

which allows you to set ```sqe->addr``` to the file descriptor of that socket, and then set ```IORING_ASYNC_CANCEL_FD``` in ```sqe->cancel_flags```. If done that way, you can request cancelation of any request for that ring that has a file assigned with the ```fd``` value set. I believe that'll work nicely for the socket case of a socket going away and canceling anything using that fd.

Totally untested...
