### ISSUE TITLE
io_uring can use unlimited memory, DoS the system: no backpressure on non-completing operations

### ISSUE THREAD

**Issue by dcolascione** [axboe/liburing#293] opened 2021-02-06 23:19 UTC
This program allocates unlimited workqueue entries in the kernel and eventually OOMs the system. (Tested on kernel 5.10.13.)

io_uring needs a better backpressure strategy. Currently, io_uring's backpressure strategy is failing work submit with EBUSY when the completion backlog is non-empty. The problem with this approach is that you can submit an unlimited number of jobs that never complete. No completion means no completion-queue filling, and no completion-queue filling means no backpressure.

```
#include <liburing.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/eventfd.h>
#include <time.h>

int main() {
    struct io_uring ring;
    int queue_max = 16;
    if (io_uring_queue_init(queue_max, &ring, 16))
        abort();
    long sqe_nr = 0;
    char dummy_buf[128];
    int my_event_fd = eventfd(0, EFD_CLOEXEC);
    if (my_event_fd < 0)
        abort();
    for (;;) {
        struct io_uring_sqe* sqe = io_uring_get_sqe(&ring);
        if (!sqe)
            break;
        io_uring_prep_read(
            sqe, my_event_fd, dummy_buf, sizeof (dummy_buf), 0);
        int ret = io_uring_submit(&ring);
        if (ret < 0) {
            printf("io_uring_submit failed: %d %s\n", -ret,
                   strerror(-ret));
            break;
        }
        sqe_nr += ret;
        printf("io_uring_submit succeeded: %ld submitted so far\n", sqe_nr);
    }
    printf("done\n");
    return 0;
}
```

**Comment by axboe** [comment] 2021-02-07 15:48
We can probably do something like this:

```
diff --git a/fs/io_uring.c b/fs/io_uring.c
index 7242cc48e97b..5223fdf1c3d3 100644
--- a/fs/io_uring.c
+++ b/fs/io_uring.c
@@ -1989,7 +1989,24 @@ static struct io_kiocb *io_get_fallback_req(struct io_ring_ctx *ctx)
 	if (!test_and_set_bit_lock(0, (unsigned long *) &ctx->fallback_req))
 		return req;
 
-	return NULL;
+	return ERR_PTR(-EAGAIN);
+}
+
+static bool io_may_alloc(struct io_ring_ctx *ctx, size_t to_alloc)
+{
+	struct io_rings *rings = ctx->rings;
+	long completions;
+
+	completions = ctx->cached_cq_tail + READ_ONCE(ctx->cached_cq_overflow);
+	/*
+	 * Somewhat arbitrary, but allow 8 times the CQ ring size. The user
+	 * rlimit accounting limits the number of rings and the size of them,
+	 * so impose a max pending limit as well.
+	 */
+	if (ctx->cached_sq_head - completions < 8 * rings->cq_ring_entries)
+		return true;
+
+	return false;
 }
 
 static struct io_kiocb *io_alloc_req(struct io_ring_ctx *ctx,
@@ -2001,6 +2018,9 @@ static struct io_kiocb *io_alloc_req(struct io_ring_ctx *ctx,
 		int ret;
 
 		sz = min_t(size_t, state->ios_left, ARRAY_SIZE(state->reqs));
+		if (unlikely(!io_may_alloc(ctx, sz)))
+			return ERR_PTR(-ENOSPC);
+
 		ret = kmem_cache_alloc_bulk(req_cachep, gfp, sz, state->reqs);
 
 		/*
@@ -6874,9 +6894,9 @@ static int io_submit_sqes(struct io_ring_ctx *ctx, unsigned int nr)
 			break;
 		}
 		req = io_alloc_req(ctx, &state);
-		if (unlikely(!req)) {
+		if (unlikely(IS_ERR(req))) {
 			if (!submitted)
-				submitted = -EAGAIN;
+				submitted = PTR_ERR(req);
 			break;
 		}
 		io_consume_sqe(ctx);
@@ -6899,7 +6919,7 @@ static int io_submit_sqes(struct io_ring_ctx *ctx, unsigned int nr)
 	}
 
 	if (unlikely(submitted != nr)) {
-		int ref_used = (submitted == -EAGAIN) ? 0 : submitted;
+		int ref_used = (submitted < 0) ? 0 : submitted;
 		struct io_uring_task *tctx = current->io_uring;
 		int unused = nr - ref_used;
 ```

which limits the total number of pending requests for the ring.

**Comment by Flowdalic** [comment] 2021-02-07 17:26
> which limits the total number of pending requests for the ring.

Which probably also limits `io_uring`s usability for applications that have a large amount of (valid) pending requests.

We also discovered this "issue", but where not sure if it is a new attack vector, or if it is simply the same class of "(malicious) application performs a large `malloc()` and touches every page of the returned memory causing an OOM situation". Is the `io_uring` resource acquisition any different? If not, why introduce an artificial limitation?

**Comment by dcolascione** [comment] 2021-02-07 19:22
> "(malicious) application performs a large malloc() and touches every page of the returned memory causing an OOM situation

These days, we at least try to prevent the scenario you're describing. A malicious application using `malloc` can be constrained in a variety of ways, e.g., a VSIZE limit or a memory control group.

Basically, our strategy seems incoherent here. We should either account both ring memory and kernel memory for outstanding objects as locked memory or leave both unaccounted and rely on `CONFIG_MEMCG_KMEM` for limiting the ability of users to make both large rings and large outstanding operation queues. It doesn't make a lot of sense to me for io_uring to count ring buffers against the locked memory size but allow applications to generate a zillion outstanding workqueue entries that don't count against the locked memory. TBH, I'd rather get rid of the locked accounting on rings.

**Comment by axboe** [comment] 2021-02-08 15:17
I don't disagree with any of that. memcg accounting might be just the right solution, if combined with Pavel's patch to make allocs persistent over io_uring_enter() invocations. Without that, it'd be cost prohibitive, as req alloc+free is part of the hot path. CC @isilence

**Comment by axboe** [comment] 2021-02-08 15:18
And if we do go that route, we could potentially get rid of rlimit memlock accounting for the rings themselves, just include them in the memcg as well. BPF recently went a similar route. Might make sense to retain rlimit memlock for registered buffers, though.

**Comment by isilence** [comment] 2021-02-08 16:07
> I don't disagree with any of that. memcg accounting might be just the right solution, if combined with Pavel's patch to make allocs persistent over io_uring_enter() invocations. Without that, it'd be cost prohibitive, as req alloc+free is part of the hot path. CC @isilence

Well, it reuses requests only when they're completed inline, so that leaves all the overhead on the async completion side. One atomic_sub or spinlocking for memcg, I guess? I did think to do recycling for async as well, but that's trickier in terms of synchronisation.

**Comment by axboe** [comment] 2021-02-08 16:23
For non-inline completion, we could potentially utilize the already held completion_lock to stuff them into a local list that can get recycled from submission if we have none available in the submit cache.

**Comment by isilence** [comment] 2021-02-08 16:30
Yeah, that what I had in mind for completions -- hack up io_req_complete(). Not nice part is that we need to do extra completion_lock during submission, but at least it's can be done loosily, e.g.

```C
int submit_sqes() {
    if (READ_ONCE(ctx->batch) > 32) {
        spin_lock(compl_lock);
        // free/recycle
        spin_unlock();
    }
}
```

Or if we want to employ it better, to do something like double buffering of request caches.

**Comment by axboe** [comment] 2021-02-08 16:32
Either double buffering, or just migrating from completion side to submission side when we have a suitable size (as in your example) would be good enough, I think.

**Comment by axboe** [comment] 2021-02-08 16:33
On the task_work side, if we go the route of having our own list for that, then we can even recycle with an ammortized completion lock cost too. Ditto IOPOLL, that one is trivial. Don't care too much about the io-wq completion side, that's not truly a fast path.

**Comment by isilence** [comment] 2021-02-08 17:02
Yeah, IOPOLL is already simple. You mean like in io_submit_flush_completions() do
but for task_work? Sounds good. I wonder what the number of our abusing of task_works,
e.g. mean QD in there.

Ok, I was planning to put back those patches at the end of the week, let's see how much we can go from there.

**Comment by axboe** [comment] 2021-02-10 15:24
Most/all of this has been fixed up and queued up for 5.12.

**Comment by dcoutts** [comment] 2021-03-29 01:31
Very closely related to this, could we document the behaviour for the man page, either the new or old (or both)? I'll volunteer to write a PR for the man page if I can understand the behaviour myself!

Let me try and elaborate the issue a bit...

Right now the man page tells us we can get

> EAGAIN The kernel was unable to allocate memory for the request, or otherwise ran out of resources  to  handle  it. The application should wait for some completions and try again.

> EBUSY  The application is attempting to overcommit the number of requests it  can  have  pending.  The  application should  wait  for  some completions and try again. May occur if the application tries to queue more requests than we have room for in the CQ ring.

The distinction between these two isn't very clear.

I think most people get that if the completion queue is full then it's reasonable to expect a failure like this, and the solution is just to process all the completions, clear the completion queue and try again.

The case that's really unclear though is if we can get either of these errors when the completion queue is empty. Of course that's exactly what this issue was about (that there was no back-pressure in this case). Presumably the new answer is yes, yes we can get one or the other of these errors even if the completion queue is empty. What are we to do in this case? Are we guaranteed that if we call `io_uring_enter` again with 0 `to_submit` and `min_complete` > 0 that we'll then be able to submit more? Or perhaps not just once but calling it repeatedly then we're _eventually_ guaranteed to be able to submit more? Presumably this would only be true when we have enough pending operations on the uring that are not-blocking (e.g. not most socket ops).

And for guidance, should we assume there's different limits or costs to different operations? e.g. blocking things like `IORING_OP_POLL_ADD` cheaper than things like `IORING_OP_OPENAT` or `IORING_OP_CONNECT`?

I ask because of course if one maxes out the memory limits using blocking operations then we could get really stuck since waiting for operations to complete could take arbitrary time. So applications (or frameworks, runtime systems etc) might want to follow a policy of allowing X blocking ops (e.g. socket things) but keeping enough space left for short-term non-blocking things like disk operations. So if we can provide some guidance on this, we can help app/framework authors handle this robustly (e.g. doing their own accounting, or imposing their own limits). e.g. how would they estimate safe limits?

Lots of questions :-). I don't expect answers to everything, but if we can get a better idea then we can document it in the man page for everyone else.

**Comment by isilence** [comment] 2021-06-18 11:58
The issue is fixed, let's close it.

@dcoutts, your message clearly got lost, sorry about that. Can you open a new issue, if you're still interested?

**Closed** 2021-06-18 12:51 UTC

**Comment by dcolascione** [comment] 2021-06-18 15:02
Thanks! Would you mind linking to the fix?

**Comment by isilence** [comment] 2021-06-20 21:03
@dcolascione, fwiw, it's now restricted by a memory cgroup

https://git.kernel.dk/cgit/linux-block/commit/?h=for-5.14/io_uring&id=91f245d5d5de0802428a478802ec051f7de2f5d6
