### ISSUE TITLE
IORING_SPLICE failed after make is called

### ISSUE THREAD

**Issue by NobodyXu** [axboe/liburing#291] opened 2021-02-05 09:34 UTC
I wrote a simple [`cat` command](https://github.com/NobodyXu/uring-utils/blob/main/src/cat.c) using `IORING_SPLICE` and it exhabits extremely strange behavior:

Every call to `cat` before `make` is called succeeds, but once `make` is called in one terminal, subsequent `cat` that **writes to the terminal** all failed. Those who write to `/dev/null` or a file like `/tmp/a` still succeeds.

I am using kernel built with `sys-kernel/gentoo-sources` with [experimental patches](https://wiki.gentoo.org/wiki/Project:Kernel/Experimental#Overview_of_experimental_patches) appliled:

```
Linux gentoo 5.10.12-gentoo #3 SMP PREEMPT Thu Feb 4 18:08:56 AEDT 2021 x86_64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz GenuineIntel GNU/Linux
```

Does anybody have a clue on what have happened?

Edit:

Strangely enough, now I am having every `cat` that takes input from terminal failed.

Even restarting the terminal or restarting the computer doesn't help.

**Comment by axboe** [comment] 2021-02-05 15:09
Well, that looks fun. I took a quick look, and if you strace what makes does, you'll find this juicy bit:

```
fcntl(1, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(1, F_SETFL, O_RDWR|O_APPEND)      = 0
fcntl(2, F_GETFL)                       = 0x402 (flags O_RDWR|O_APPEND)
fcntl(2, F_SETFL, O_RDWR|O_APPEND)      = 0
```

where it sets O_APPEND on fd 1+2. splice(2) (and IORING_OP_SPLICE subsequently) doesn't work in append mode, and hence your test case will fail since that has been set.

A bit buggy of make to do that and not undo it, but I guess you could work around it by clearing O_APPEND with F_GETFL/F_SETFL as part of your startup.

**Comment by axboe** [comment] 2021-02-05 15:14
Adding this to the top of your main():

```
    int flags;

    flags = fcntl(out_fd, F_GETFL);
    if (flags & O_APPEND) {
	    flags &= ~O_APPEND;
	    fcntl(out_fd, F_SETFL, flags);
    }
```

makes it work fine regardless of what ```make``` has been up to, as expected.

**Comment by NobodyXu** [comment] 2021-02-05 22:04
@axboe Thanks, this has fixed the problem.

But now there's another problem: all of a sudden `./cat` cannot take input from terminal, but still can write to it.
I don't know how this happens and I have rebooted my computer several time.

Can you borrow me some help? This is really confusing.

**Comment by axboe** [comment] 2021-02-05 22:07
Sure, but please be specific in how to reproduce this. Much easier for me to look into something that way, instead of having to spend time guessing how to reproduce the failure.

**Comment by NobodyXu** [comment] 2021-02-05 22:15
I would like to give more clue, but currently I have no idea what have caused it to happen in the first place.

What I can observe is that every `./cat` that takes input from the terminal failed with `EINVAL` for `IORING_OP_`SPLICE.

**Comment by axboe** [comment] 2021-02-05 22:20
Maybe O_APPEND is set on that too? Have you tried clearing it like for out_fd. Just a guess, many reasons why you'd get EINVAL, but none of them are really io_uring...

**Comment by NobodyXu** [comment] 2021-02-06 02:40
I just confirmed this strange behavior with debian 11.

On its freshly installed `Linux localhost 5.10.0-2-amd64 #1 SMP Debian 5.10.9-1 (2021-01-20) x86_64 GNU/Linux` kernel, this 
strange behavior can be reproduced.

**Comment by axboe** [comment] 2021-02-06 02:45
I can't reproduce it, which is why I'm asking. I'll try 5.10-stable as well, I've been running newer stuff. But it works just fine there:

```
$ ./icat < a.c  |less
```

or

```
$ cat a.c | ./icat |less
```

Won't have time before Monday, JFYI.

**Comment by NobodyXu** [comment] 2021-02-06 02:58
Can you try:

```
./cat
```

or 

```
./cat | cat
```

Commands that takes input from terminal directly failed on my computer and debian-11

**Comment by axboe** [comment] 2021-02-06 03:19
I think you'll find the same issue with splice, io_uring is just using the same underlying mechanism. tty file operations don't support splice_read. This could be added, but it's really outside of io_uring as it's not an io_uring issue...

**Comment by NobodyXu** [comment] 2021-02-06 03:29
Thanks for replying, I guess I will then avoid using `splice` for reading from terminal.

**Comment by axboe** [comment] 2021-02-06 03:49
Yeah, it has nothing to do with O_APPEND. It's really a fallout from this change:

```
commit 36e2c7421f02a22f71c9283e55fdb672a9eb58e7
Author: Christoph Hellwig <hch@lst.de>
Date:   Thu Sep 3 16:22:34 2020 +0200

    fs: don't allow splice read/write without explicit ops
```

which has seen a number of fixes since... I'll try and talk to Christoph, but at least for now you're just out of luck :-(

**Comment by NobodyXu** [comment] 2021-02-06 03:53
I found a [bug report](https://bugzilla.kernel.org/show_bug.cgi?id=209971) which claimed this is fixed in [commit 14e3e989f6a5d9646b6cf60690499cc8bdc11f7d](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=14e3e989f6a5d9646b6cf60690499cc8bdc11f7d)

**Comment by NobodyXu** [comment] 2021-02-06 04:00
> I'll try and talk to Christoph, but at least for now you're just out of luck :-(

@axboe Thank you very much

**Comment by axboe** [comment] 2021-02-06 21:05
Christoph says that Linus already did the read_iter/splice_read for 5.12, so it'll end up going to -stable in a few weeks. So there's hope, it'll work soon in -stable.

Closing this one.

**Closed by axboe** 2021-02-06 21:05 UTC
